import_name: 'Keys'
namespace: 'Keys'
result_path: 'Packages/'
swift_declaration_strategy: let
should_generate_unit_tests: true
package_manager: spm
environments:
  - Debug
  - Alpha
  - Beta
  - Release
global_secrets:
  - sentryDSN
environment_secrets:
  - applePayMerchantID
  - googleMapsAPIKey