// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol KeysGlobalProtocol {
    var newRelicAPIKey: String { get }
}

public protocol KeysEnvironmentProtocol {
    var applePayMerchantID: String { get }
    var googleMapsAPIKey: String { get }
}
