# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

fastlane_require 'colored'
fastlane_require 'yaml'
fastlane_require 'json'
fastlane_require 'dotenv'

import './modules/onboarder.rb'

# Uncomment the line if you want fastlane to automatically update itself
default_platform(:ios)

platform :ios do
  before_all do
    setup_environment
  end

  desc "Sets up Environment Variables"
  lane :setup_environment do
    UI.header "Setting up Environment Variables..."

    Dotenv.load "configs/.env.default.auth"
    Dotenv.load "configs/.env.default.project"

    UI.success "Environment Variables are set up successfully!"
  end
end
