// swift-tools-version: 5.6

// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import PackageDescription

let package = Package(
    name: "Keys",
    platforms: [
        .macOS(.v11),
        .iOS(.v11),
        .tvOS(.v11),
        .watchOS(.v4),
    ],
    products: [
        .library(
            name: "Keys",
            targets: ["Keys"]
        ),
    ],
    dependencies: [
        .package(name: "KeysInterfaces", path: "../KeysInterfaces"),
    ],
    targets: [
        .target(
            name: "Keys",
            dependencies: ["KeysInterfaces"],
            path: "Sources"
        ),
        .testTarget(
            name: "KeysTests",
            dependencies: ["Keys"],
            path: "Tests"
        ),
    ]
)
