name: Distribute to TestFlight

on:
  push:
    branches:
      - main

jobs:
  distribute:
    runs-on: macos-13
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Set up environment variables
        run: |
          echo "${{ secrets.FASTLANE_ENV_AUTH_FILE }}" > fastlane/configs/default/.env.default.auth
          echo "${{ secrets.ARKANA_ENV_AUTH_FILE }}" > .env
        shell: bash

      - uses: jdx/mise-action@v2
        with:
          version: 2024.8.15 # [default: latest] mise version to install
          install: false # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache

      - name: Setup Certs and Profiles on CI
        run: |
          bundle exec fastlane ci_import_certs_profiles_locally

      - name: Generate Project
        run: |
          bundle exec fastlane generate_project

      - name: Distribute to TestFlight
        run: |
          bundle exec fastlane distribute_to_appstore env:"ALPHA"