name: CI Checks

on:
  pull_request:

jobs:
  build_test:
    runs-on: macos-13
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Setup Homebrew Dependencies
        run: |
          brew bundle
      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          version: 2024.8.15
          install: false
          cache: true
      - name: Set up environment variables
        run: |
          echo "${{ secrets.FASTLANE_ENV_AUTH_FILE }}" > fastlane/configs/default/.env.default.auth
          echo "${{ secrets.ARKANA_ENV_AUTH_FILE }}" > .env
      
      - name: Generate Project
        run: |
          bundle exec fastlane generate_project
          tuist generate
      
      - name: Check if Tests pass
        run: |
          tuist test
  danger:
    runs-on: macos-13
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true

    - uses: MeilCli/danger-action@v6
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_TOKEN }}