name: Distribute to TestFlight

on:
  push:
    branches:
      - m04-02-improvements

jobs:
  distribute:
    runs-on: macos-13
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Set up environment variables
        run: |
          echo "${{ secrets.FASTLANE_ENV_AUTH_FILE }}" > fastlane/configs/default/.env.default.auth
          echo "${{ secrets.ARKANA_ENV_AUTH_FILE }}" > .env
        shell: bash

      - uses: jdx/mise-action@v2
        with:
          version: 2024.8.15 # [default: latest] mise version to install
          install: false # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache

      - name: Setup Certs and Profiles on CI
        run: |
          bundle exec fastlane prepare_ci_certs_profiles

      - name: Distribute to TestFlight
        run: |
          bundle exec fastlane distribute_to_testflight env:"ALPHA"

      # Load environment variables from .env file
# For Day 8
      # - name: Load .env file
      #   run: |
      #     set -a  # Automatically export all variables
      #     source fastlane/configs/ci/.env.default.ci.match
      #     set +a

      # - name: Install the Apple certificate and provisioning profile
      #   env:
      #     BUILD_CERTIFICATE_BASE64: $BUILD_CERTIFICATE_BASE64
      #     BUILD_PROVISION_PROFILE_BASE64: $BUILD_PROVISION_PROFILE_BASE64
      #     KEYCHAIN_PASSWORD: $KEYCHAIN_PASSWORD
      #   run: |
      #     CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
      #     PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
      #     KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
      
      #     # Decode certificate and provisioning profile
      #     echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
      #     echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
      
      #     # Create and configure a temporary keychain
      #     security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      #     security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
      #     security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      
      #     # Import the certificate without a password
      #     security import $CERTIFICATE_PATH -A -k $KEYCHAIN_PATH
      
      #     # Set partition list to allow codesigning tools access to the keychain
      #     security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      
      #     # Add the keychain to the keychain search path
      #     security list-keychain -d user -s $KEYCHAIN_PATH
      
      #     # Copy provisioning profile to the appropriate directory
      #     mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
      #     cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
        